packages <- c("knitr", "markdown")
sapply(packages, require, character.only = TRUE, quietly = TRUE)
setwd("/Users/Jostein/Projects/datasciencecoursera/data-cleaning")
knit("run_analysis.Rmd", encoding = "ISO8859-1")
knit("codebook.Rmd", encoding = "ISO8859-1")
markdownToHTML("run_analysis.md", "run_analysis.html")
markdownToHTML("codebook.md", "codebook.html")
